from .administrador import Administrador
from .alumno import Alumno
from .curso import Curso
from .docente import Docente
from .dominar import Dominar
from .editar import Editar
from .idioma import Idioma
from .inscribir import Inscribir
from .manejar import Manejar
from .recurso import Recurso
from .usuario import Usuario